chore: update CI and build process (#51)

diff --git a/scripts/build-dll b/scripts/build-dll
--- a/scripts/build-dll
+++ b/scripts/build-dll
@@ -17,8 +17,21 @@ function build-dll() {
     return 0
   fi
 
+  # a windows version (e.g. 2019, 2022) must be provided as the second argument
+  if [ -z "${2}" ]; then
+    echo "error: a Windows version argument (e.g. 2019, 2022) is required"
+    exit 1
+  fi
+
+  DIGEST=$(yq e ".dotnet.${2}.shasum" build.yaml)
+
+  if [ -z "${DIGEST}" ] || [ "${DIGEST}" = "null" ]; then
+    echo "error: no dotnet shasum found in build.yaml for version '${2}'"
+    exit 1
+  fi
+
   # build the DLL in a container so we don't have to install .NET SDK's on the runner
-  docker build --no-cache -f package/ccg-plugin-installer/Dockerfile.builder.windows -t rancher/gmsa-ccg-plugin-builder  .
+  docker build --no-cache --build-arg "DIGEST=${DIGEST}" -f package/ccg-plugin-installer/Dockerfile.builder.windows -t rancher/gmsa-ccg-plugin-builder .
   docker create --name dllbuild rancher/gmsa-ccg-plugin-builder:latest
 
   # cp the resulting artifact into the manager directory so we can embed the file on build
@@ -28,4 +41,4 @@ function build-dll() {
   docker rm dllbuild
 }
 
-build-dll ${OS}
+build-dll ${OS} ${1}
diff --git a/scripts/charts-build-scripts/pull-scripts b/scripts/charts-build-scripts/pull-scripts
--- a/scripts/charts-build-scripts/pull-scripts
+++ b/scripts/charts-build-scripts/pull-scripts
@@ -21,15 +21,37 @@ mkdir -p bin
 OS=$(go version | cut -d' ' -f4 | cut -d'/' -f1)
 ARCH=$(go version | cut -d' ' -f4 | cut -d'/' -f2)
 if [[ ${OS} == "linux" ]]; then
-    BINARY_NAME=charts-build-scripts
+    if [[ ${ARCH} == "amd64" ]]; then
+        EXPECTED_SHASUM=${CHARTS_BUILD_SCRIPT_SHASUM_LINUX_AMD}
+    elif [[ ${ARCH} == "arm64" ]]; then
+        EXPECTED_SHASUM=${CHARTS_BUILD_SCRIPT_SHASUM_LINUX_ARM}
+    fi
+    BINARY_NAME=charts-build-scripts_${OS}_${ARCH}
 else
-    BINARY_NAME=charts-build-scripts-${OS}
+    if [[ ${OS} != "darwin" ]]; then
+        echo "Unsupported OS: ${OS}, will build from source"
+        FORCE_BUILD="true"
+    fi
+    if [[ ${ARCH} == "amd64" ]]; then
+        EXPECTED_SHASUM=${CHARTS_BUILD_SCRIPT_SHASUM_DARWIN_AMD}
+    elif [[ ${ARCH} == "arm64" ]]; then
+        EXPECTED_SHASUM=${CHARTS_BUILD_SCRIPT_SHASUM_DARWIN_ARM}
+    fi
+    BINARY_NAME=charts-build-scripts_${OS}_${ARCH}
 fi
-if [[ ${ARCH} == "amd64" ]]; then
-    # skip non-amd64 builds since rancher/charts-build-scripts does not support it yet
-    curl -s -L ${CHARTS_BUILD_SCRIPTS_REPO%.git}/releases/download/${CHARTS_BUILD_SCRIPT_VERSION}/${BINARY_NAME} --output bin/charts-build-scripts
+
+if [[ "${FORCE_BUILD}" != "true" ]]; then
+  echo "downloading build scripts from ${CHARTS_BUILD_SCRIPTS_REPO%.git}/releases/download/${CHARTS_BUILD_SCRIPT_VERSION}/${BINARY_NAME}"
+  curl -s -L ${CHARTS_BUILD_SCRIPTS_REPO%.git}/releases/download/${CHARTS_BUILD_SCRIPT_VERSION}/${BINARY_NAME} --output bin/charts-build-scripts
+  RECEIVED_SHASUM=$(cat bin/charts-build-scripts | sha256sum | cut -d' ' -f1)
+  if [[ "${RECEIVED_SHASUM}" != "${EXPECTED_SHASUM}" ]]; then
+      echo "Shasum verification failed for downloaded charts-build-scripts binary. Expected ${EXPECTED_SHASUM} but got ${RECEIVED_SHASUM}"
+      rm bin/charts-build-scripts
+      exit 1
+  fi
 fi
-if ! [[ -f bin/charts-build-scripts ]] || [[ "$(cat bin/charts-build-scripts)" == "Not Found" ]]; then
+
+if ! [[ -f bin/charts-build-scripts ]] || [[ "$(cat bin/charts-build-scripts)" == "Not Found" ]] || [[ "$FORCE_BUILD" == "true" ]]; then
     [[ -f bin/charts-build-scripts ]] && rm bin/charts-build-scripts; 
     
     # Fall back to old process
@@ -48,10 +70,12 @@ if ! [[ -f bin/charts-build-scripts ]] || [[ "$(cat bin/charts-build-scripts)" =
     trap 'cleanup' EXIT
     
     [[ -d charts-build-scripts ]] && rm -rf charts-build-scripts
-    git clone --depth 1 --branch $CHARTS_BUILD_SCRIPT_VERSION $CHARTS_BUILD_SCRIPTS_REPO 2>/dev/null
+    echo "cloning $CHARTS_BUILD_SCRIPTS_REPO@$CHARTS_BUILD_SCRIPT_VERSION_COMMIT into ${TEMP_DIR}"
+    git clone --depth 1 --revision $CHARTS_BUILD_SCRIPT_VERSION_COMMIT $CHARTS_BUILD_SCRIPTS_REPO 2>/dev/null
 
     cd charts-build-scripts
-    VERSION_OVERRIDE=${CHARTS_BUILD_SCRIPT_VERSION} ./scripts/build
+    mkdir bin
+    go build -ldflags "-s -w -X main.Version=${CHARTS_BUILD_SCRIPT_VERSION} -X main.GitCommit=${CHARTS_BUILD_SCRIPT_VERSION_COMMIT}" -o bin/charts-build-scripts .
     mv bin/charts-build-scripts ${CURR_DIR}/bin/charts-build-scripts
     
     # Return to original directory
